# Generated by Django 4.2.7 on 2024-12-13 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_materia',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='t_proyectos',
            name='T_Fase_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.t_fase_proyecto', verbose_name='Fase del Proyecto'),
        ),
        migrations.AlterField(
            model_name='t_proyectos',
            name='T_Gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.t_gestion', verbose_name='Gestion'),
        ),
        migrations.AlterField(
            model_name='t_proyectos',
            name='T_Materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.t_materia', verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='t_proyectos',
            name='T_Tipo_Proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.t_tipo_proyecto', verbose_name='Tipo de Proyecto'),
        ),
    ]
